version: '3.9'

x-base_service: &base_service
  ports:
    - "${WEBUI_PORT:-7860}:7860"
  volumes:
    - &v1 ./data:/mnt/data
    - &v2 ./output:/mnt/output
  stop_signal: SIGKILL
  tty: true
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: [ '0' ]
            capabilities: [ compute, utility ]

services:
  auto:
    <<: *base_service
    image: registry.cn-shanghai.aliyuncs.com/jerryliang/stable_diffusion:latest
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
